#!/usr/bin/env node
// One-shot non-interactive rebrand to aibrake.dev.
// Generated by Claude during the rebrand. Safe to delete after commit.
//
// Run:
//   node scripts/_apply-aibrake.mjs
//
// Same logic as scripts/configure-for-deploy.mjs but with hardcoded values
// (the interactive readline doesn't accept piped stdin reliably in this
// host's shell).

import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const repoRoot = resolve(__dirname, "..");

const SKIP_DIRS = new Set(["node_modules", "dist", ".git", "validation-log", "logs", ".vitest", "coverage", "build"]);
const SKIP_EXTS = new Set([".png", ".jpg", ".jpeg", ".gif", ".pdf", ".docx", ".pyc", ".log"]);
const SKIP_FILES = new Set(["package-lock.json"]);

const TEST_OR_DOC_DENYLIST = new Set([
  "tests/stage-04-2-sdk-fail-open-scope.test.ts",
  "tests/stage-05-partner-ready-hardening.test.ts",
  "python/tests/test_client.py",
  "python/tests/test_integration.py",
  "python/tests/conftest.py",
  "python/Dockerfile.test",
  "SELF_TRIAL_CLAUDE_CODE_LOG.md",
  "SELF_TRIAL_CLAUDE_CODE_REPORT.md",
  "BENCHMARK_10_AGENTS.md",
  "scripts/self-trial-guard.ts",
  "scripts/simulate-10-partners.ts",
  "scripts/simulate-100-partners-week.ts",
  "scripts/_apply-aibrake.mjs",
]);

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue;
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

function rel(p) { return p.slice(repoRoot.length + 1).replaceAll("\\", "/"); }

// Order matters: longer/more-specific first.
const swaps = [
  ["api.agentspendguard.example.com", "api.aibrake.dev"],
  ["api.agentspendguard.com",          "api.aibrake.dev"],
  ["beta@agentspendguard.example",     "beta@aibrake.dev"],
  ["hello@agentspendguard.example",    "hello@aibrake.dev"],
  ["agentspendguard.example.com",      "aibrake.dev"],
  ["agentspendguard.example",          "aibrake.dev"],
  ["agentspendguard.com",              "aibrake.dev"],
  ["your-org/spending-guard",          "Askbsman/aibrake"],
];

const allFiles = walk(repoRoot);
let changed = 0;
const list = [];

for (const abs of allFiles) {
  const r = rel(abs);
  if (TEST_OR_DOC_DENYLIST.has(r)) continue;
  const ext = r.slice(r.lastIndexOf("."));
  if (SKIP_EXTS.has(ext)) continue;
  const base = r.split("/").pop();
  if (SKIP_FILES.has(base)) continue;

  let content;
  try { content = readFileSync(abs, "utf8"); } catch { continue; }
  let next = content;
  for (const [from, to] of swaps) {
    if (from === to) continue;
    next = next.split(from).join(to);
  }
  if (next !== content) {
    writeFileSync(abs, next, "utf8");
    changed += 1;
    list.push(r);
  }
}

console.log(`Done. ${changed} files updated.`);
for (const f of list) console.log(`  ${f}`);
